vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /media/properties # dossier ou on va envoyer notre image
            upload_destination: '%kernel.project_dir%/public/media/properties'  # ou on va envoyer les differents fichiers
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
